import fetch from 'node-fetch';

async function tryEndpoint(url, body) {
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  return { ok: res.ok, status: res.status, text };
}

export async function generateWithGemini(prompt) {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('Missing GEMINI_API_KEY on server');
  }

  const p = String(prompt || '').trim();
  if (!p) throw new Error('Empty prompt');

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`;
  
  const body = {
    contents: [
      {
        parts: [
          {
            text: p
          }
        ]
      }
    ],
    generationConfig: {
      temperature: 0.7,
      topK: 1,
      topP: 1,
      maxOutputTokens: 2048,
      stopSequences: []
    },
    safetySettings: [
      {
        category: "HARM_CATEGORY_HARASSMENT",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      },
      {
        category: "HARM_CATEGORY_HATE_SPEECH",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      },
      {
        category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      },
      {
        category: "HARM_CATEGORY_DANGEROUS_CONTENT",
        threshold: "BLOCK_MEDIUM_AND_ABOVE"
      }
    ]
  };

  try {
    const { ok, status, text } = await tryEndpoint(url, body);
    console.log(`[GEMINI] API call -> status ${status} preview:`, text.slice(0, 400));

    if (!ok) {
      console.error(`[GEMINI] API error ${status}:`, text);
      if (status === 403) {
        throw new Error('Gemini API access denied. Please check your API key and ensure the Generative Language API is enabled in Google Cloud Console.');
      } else if (status === 404) {
        throw new Error('Gemini API endpoint not found. The model may not be available.');
      } else if (status === 429) {
        throw new Error('Gemini API rate limit exceeded. Please try again later.');
      } else {
        throw new Error(`Gemini API error ${status}: ${text}`);
      }
    }

    let data;
    try { 
      data = JSON.parse(text); 
    } catch (e) { 
      throw new Error(`Invalid JSON response from Gemini API: ${text}`);
    }

    const candidateText = 
      data?.candidates?.[0]?.content?.parts?.[0]?.text ||
      data?.candidates?.[0]?.output ||
      null;

    if (candidateText) {
      return candidateText;
    }

    console.error('[GEMINI] Unexpected response structure:', JSON.stringify(data, null, 2));
    throw new Error('No text generated by Gemini API. Response: ' + JSON.stringify(data));

  } catch (err) {
    console.error('[GEMINI] Error:', err.message);
    throw err;
  }
}
